version: '3.7'

services:
  db:
    image: postgres:15.3  # Specify a specific version
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - default

volumes:
  postgres_data:

networks:
  default: